version: '3.8'
services:
  my-portfolio:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - backend-net

  monitor:
    image: nginx:latest
    networks:
      - backend-net

networks:
    backend-net:
      driver: bridge
