version: '3.8'
services:
  app-web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - backend-net

  database-sim:
    image: httpd:latest
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
